name: proyecto_i3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - dm-sonnet==1.36
      - tensorflow-macos
      - tensorflow-metal
      - tensorflow-probability==0.8.0
